// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level lifecycle/UI state surfaced to the user at all times (FR-4).
 */
export type AppState = "stopped" | "connecting" | "listening" | "thinking" | "speaking" | "reconnecting" | "error";
