// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection status detail surfaced via the `connection` event (SPEC §11.3).
 */
export type ConnectionStatus = "disconnected" | "connecting" | "connected" | "reconnecting";
