// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of the current history, surfaced to the UI (SPEC §11, `history` event).
 */
export type HistoryMeta = { 
/**
 * Number of stored turns.
 */
turns: number, 
/**
 * Sum of per-turn token estimates.
 */
token_estimate: number, 
/**
 * The configured budget.
 */
budget: number, };
