// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point-in-time throughput sample surfaced to the UI as [`crate::session::UiEvent::Metrics`].
 *
 * All three figures are instantaneous rates over the most recent [`SAMPLE_INTERVAL`] window, so
 * the frontend can render a live up/down bandwidth + generation-speed indicator without doing any
 * math of its own (the architecture rule: logic in Rust, the UI only renders).
 */
export type MetricsSnapshot = { 
/**
 * Upstream rate to the provider in kbit/s — actual WebSocket frame bytes (base64+JSON) when the
 * provider reports them, otherwise a payload-level estimate (mic audio + screen frames + text).
 */
up_kbps: number, 
/**
 * Downstream rate from the provider in kbit/s — actual WebSocket frame bytes when reported,
 * otherwise a payload-level estimate (synthesized audio + transcripts).
 */
down_kbps: number, 
/**
 * Agent output generation rate in tokens per second (chars/4 — see `history::estimate_tokens`).
 */
tokens_per_sec: number, };
