// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point-in-time throughput sample surfaced to the UI as [`crate::session::UiEvent::Metrics`].
 *
 * All four figures are instantaneous rates over the most recent [`SAMPLE_INTERVAL`] window, so
 * the frontend can render a live up/down bandwidth + up/down token-rate indicator without doing
 * any math of its own (the architecture rule: logic in Rust, the UI only renders).
 */
export type MetricsSnapshot = { 
/**
 * Upstream rate to the provider in kbit/s — actual WebSocket frame bytes (base64+JSON) when the
 * provider reports them, otherwise a payload-level estimate (mic audio + screen frames + text).
 */
up_kbps: number, 
/**
 * Downstream rate from the provider in kbit/s — actual WebSocket frame bytes when reported,
 * otherwise a payload-level estimate (synthesized audio + transcripts).
 */
down_kbps: number, 
/**
 * Upstream token rate in tokens/s — **input** tokens the provider is consuming (audio + video +
 * text, all modalities). From Gemini's real `usageMetadata.promptTokenCount` differenced over
 * the window when available; otherwise a chars/4 estimate of sent text only.
 */
up_tokens_per_sec: number, 
/**
 * Downstream token rate in tokens/s — **output** tokens the model is generating. From Gemini's
 * real `usageMetadata.responseTokenCount` differenced over the window when available; otherwise
 * a chars/4 estimate of the output transcript.
 */
down_tokens_per_sec: number, };
