// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the provider's API is reachable, from the token-free background probe (see
 * [`crate::connectivity`]). Distinct from [`ConnectionStatus`], which tracks a *live session's*
 * socket; reachability is meaningful even with no session running.
 */
export type Reachability = "unknown" | "checking" | "online" | "unauthorized" | "offline";
