// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is speaking in a transcript line (SPEC §4).
 */
export type Speaker = "user" | "agent";
