// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal UI settings (SPEC §8, §13).
 */
export type TerminalCfg = { 
/**
 * ANSI theme name.
 */
theme: string, 
/**
 * Monospace font family.
 */
font: string, 
/**
 * Scrollback line count.
 */
scrollback: number, };
