// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalCfg } from "./TerminalCfg";

/**
 * Web-frontend settings — delivered to the UI by the host; not used by the engine itself.
 */
export type UiCfg = { 
/**
 * Terminal appearance.
 */
terminal: TerminalCfg, };
