// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { ConnectionStatus } from "./ConnectionStatus";
import type { HistoryMeta } from "./HistoryMeta";
import type { Speaker } from "./Speaker";

/**
 * UI-facing event emitted to the webview (SPEC §11.3). Audio is **not** here — it streams over the
 * binary `tauri::ipc::Channel` (SPEC §11.2).
 */
export type UiEvent = { "type": "state", 
/**
 * The new state.
 */
state: AppState, } | { "type": "transcript", 
/**
 * Who spoke.
 */
speaker: Speaker, 
/**
 * The text.
 */
text: string, 
/**
 * Whether this line is finalized. Serializes as `final` (m-4 raw-keyword dodge).
 */
final: boolean, } | { "type": "connection", 
/**
 * The status.
 */
status: ConnectionStatus, 
/**
 * Optional human-readable detail.
 */
detail: string | null, } | { "type": "history" } & HistoryMeta | { "type": "error", 
/**
 * Short machine-ish kind.
 */
kind: string, 
/**
 * Human-readable message.
 */
message: string, };
